version: 0.2

phases:
  
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=703671905249.dkr.ecr.us-east-1.amazonaws.com/my-project-repo 

  build:
    commands:
      # Build the Docker image
      - echo "Building Docker image"
      - docker build -t "$REPOSITORY_URI/simple-python-flask-app:latest" .

  post_build:
    commands:
      # Push the Docker image to ECR
      - echo "Pushing Docker image to ECR"
      - docker push "$REPOSITORY_URI/simple-python-flask-app:latest"
      - echo "Docker image pushed successfully!"

artifacts:
  files:
    - '**/*'
