version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      # Installing AWS CLI and Docker (if not already present)
      - echo "Installing dependencies"
      - aws --version
      - docker --version
  pre_build:
    commands:
      # Setting up AWS ECR login
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=703671905249.dkr.ecr.us-east-1.amazonaws.com/my-project-repo  # Change this with your ECR repository URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')  # You can use a dynamic tag, e.g., $(date +%Y%m%d%H%M%S) or git commit hash
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      # Build the Docker image
      - echo "Building Docker image"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      # Push the Docker image to ECR
      - echo "Pushing Docker image to ECR"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker image pushed successfully!"

artifacts:
  files:
    - '**/*'
